{
  "TYPES.Actor.actor": "Actor",
  "AETHERCHROME.ActorSheet": "Aetherchrome Actor Sheet",
  "AETHERCHROME.Name": "Actor Name",
  "AETHERCHROME.Concept": "Concept",
  "AETHERCHROME.Attributes": "Attributes",
  "AETHERCHROME.AttributeRangeNote": "Standard range 1–9; Current may reach 0",
  "AETHERCHROME.Base": "Base",
  "AETHERCHROME.Current": "Current",
  "AETHERCHROME.AttributeStrength": "Strength",
  "AETHERCHROME.AttributeHealth": "Health",
  "AETHERCHROME.AttributeIntelligence": "Intelligence",
  "AETHERCHROME.AttributeAgility": "Agility",
  "AETHERCHROME.AttributeCharisma": "Charisma",
  "AETHERCHROME.AttributeEssence": "Essence",
  "AETHERCHROME.Skills": "Skills",
  "AETHERCHROME.SkillRangeNote": "Base Skill range 0–10",
  "AETHERCHROME.Use": "Use",
  "AETHERCHROME.SkillName": "Skill",
  "AETHERCHROME.GoverningAttribute": "Governing Attribute",
  "AETHERCHROME.Rating": "Rating",
  "AETHERCHROME.SkillPlaceholder": "Enter Skill name",
  "AETHERCHROME.Resources": "Secondary Attributes",
  "AETHERCHROME.HealthCurrent": "Current HP",
  "AETHERCHROME.HealthMaximum": "Maximum HP",
  "AETHERCHROME.Diagnostics": "Diagnostics",
  "AETHERCHROME.RollDiagnostic": "Roll Diagnostic d10",
  "AETHERCHROME.DiagnosticNote": "This confirms dice evaluation and chat output. It is not the Skill Pool mechanic.",
  "AETHERCHROME.Notes": "Notes",
  "AETHERCHROME.Save": "Save",
  "AETHERCHROME.SkillTree": "Skill Tree",
  "AETHERCHROME.SkillTreeNote": "Registered Alpha topology; ratings 0–10",
  "AETHERCHROME.Task": "Available Task",
  "AETHERCHROME.SelectTask": "Select Task…",
  "AETHERCHROME.NoRegisteredTasks": "No registered Tasks",
  "AETHERCHROME.TaskDetailsRoll": "Task Details and Roll",
  "AETHERCHROME.SecondaryAttributes": "Secondary Attributes",
  "AETHERCHROME.Maximum": "Maximum",
  "AETHERCHROME.ItemSheet": "Aetherchrome Item Sheet"
}
